INSERT INTO TEACHERS
VALUES (1, 'Konoha, Centro - condominio do sábio, apt 501', 'Hatake Kakashi', '(54)9833-5707');

INSERT INTO TEACHERS 
VALUES (2, 'Konoha, clã Sarutobi', 'Sarutobi Asuma', '(54)9945-5790');


INSERT INTO CLASSROOMS 
VALUES (1, 1, 'TIME 7');

INSERT INTO CLASSROOMS 
VALUES (2, 2, 'TIME 10');

INSERT INTO STUDENTS
VALUES (1, 1, 'Uzumaki Naruto', true);

INSERT INTO STUDENTS
VALUES (2, 1, 'Uchiha Sasuke', true);

INSERT INTO STUDENTS
VALUES (3, 1, 'Haruno Sakura', true);

INSERT INTO STUDENTS
VALUES (4, 2 , 'Nara Shikamaru', true);

INSERT INTO STUDENTS
VALUES (5, 2 , 'Yamanaka Ino', true);

INSERT INTO STUDENTS
VALUES (6, 2 , 'Akimichi Chouji', true);

ALTER TABLE TEACHERS
ALTER COLUMN TEACHER_ID RESTART WITH 3;

ALTER TABLE CLASSROOMS
ALTER COLUMN CLASSROOM_ID RESTART WITH 3;

ALTER TABLE STUDENTS
ALTER COLUMN STUDENT_ID RESTART WITH 7;